version: '3.8'

services:
  sqlserver:
    build: .
    container_name: sqlserver-container
    image: sqlserver-image
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: YourStrong@Password
      ACCEPT_EULA: Y
      MSSQL_PID: Express
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
